### ISSUE TITLE
/t new <name>

### ISSUE THREAD

**Issue by FiveEYZ** [MyEssentials/MyTown2#234] opened 2015-06-17 23:12 UTC
user getting error trying to make a new town http://pastebin.com/Nmj6SSr3

**Comment by AfterWind** [comment] 2015-06-17 23:25
It seems like the town with name "Eden" already exists in the database. Try doing /t list and see if that is true.

**Comment by AfterWind** [comment] 2015-06-17 23:36
Duplicate of #233. Closing.

**Closed by AfterWind** 2015-06-17 23:36 UTC

**Comment by FiveEYZ** [comment] 2015-06-17 23:43
yes that town name Eden already existed, thanks for awesome support! :D
