### ISSUE TITLE
Crash with some protections

### ISSUE THREAD

**Issue by Esctogrillo** [MyEssentials/MyTown2#473] opened 2016-03-18 22:44 UTC
Using minecraft, Chisel2, Extra Utilities, TConstruct, Thermal Expansion and/or Thaumcraft my server crashes: http://pastebin.com/07JwbM30

This started to happen after I formated my server (and reinstall all the stuff).

**Comment by AfterWind** [comment] 2016-03-19 12:19
Pretty sure you're missing ReflectASM. Make sure you have all the jar files listed in issue #464 in the mods folder.

**Comment by AfterWind** [comment] 2016-03-19 12:38
Closed. Duplicate of #464.

**Closed by AfterWind** 2016-03-19 12:38 UTC
