### ISSUE TITLE
[MyTown2-1.7.10-0.0.2b] Town enter false flag problem

### ISSUE THREAD

**Issue by brunyman** [MyEssentials/MyTown2#188] opened 2015-05-04 08:07 UTC
We got a problem when setting a town enter flag to false, if someone try to enter that player get's stuck as the mod refuse him to allow to enter but he can't go back or tp anywhere it's just stuck there.

**Comment by evernife** [comment] 2015-05-04 09:44
Already repported by me, he is working on it.

refference to #176

**Comment by evernife** [comment] 2015-05-04 09:45
Suggestion to you, use the .json files (config) to turn this flag off, is the only way to prevent this things. For now, of course :D

**Comment by AfterWind** [comment] 2015-05-04 12:56
I am aware of the bug, still trying to fix it, but it proves to be very difficult for some reason.

**Comment by evernife** [comment] 2015-05-04 15:41
cant you try to copy the same system used by forge essentials ? Force the player teleport to the sides of the town.

**Comment by AfterWind** [comment] 2015-05-04 16:04
I could and already did, but which side, if it's an arbitrary side then we risk sending people into lava or down a cliff and die, I don't want that.

**Comment by evernife** [comment] 2015-05-04 16:07
make sence, cant you sand back in time? for exemple, a few ticks back, or back to the same side where this person enter.

**Comment by AfterWind** [comment] 2015-05-04 16:21
That's what I am doing in the current version, sending back to the position they were the last tick, but Forge doesn't want to behave so I need an alternative.

Sending them from the same side is extremely similar programmatically with the first suggestion, so we'll stick with that.

**Comment by evernife** [comment] 2015-05-04 20:14
:D

**Comment by AfterWind** [comment] 2015-06-04 16:49
Duplicate of #176. Closing

**Closed by AfterWind** 2015-06-04 16:49 UTC
Labels: duplicate
