### ISSUE TITLE
Dynmap integration

### ISSUE THREAD

**Issue by Zerzix** [MyEssentials/MyTown2#193] opened 2015-05-07 20:57 UTC
It would be nice to see towns displayed in Dynmap for forge.

**Comment by AfterWind** [comment] 2015-05-07 21:03
Duplicate of #27.
I will get to it once we have a client-side version of the mod :)

**Closed by AfterWind** 2015-05-07 21:03 UTC
Labels: client-side, duplicate

**Comment by cjm721** [comment] 2015-05-07 22:23
Dynmap is a server side map to allow connections from a web browser. Its not something you install on the client.

**Comment by AfterWind** [comment] 2015-05-07 22:29
I am aware of that, it's just scheduled after I release the client-side simply because it will have lots of the same code.
