### ISSUE TITLE
And another one, now we got crash. :) Isn't this a bit unstable, guys?

### ISSUE THREAD

**Issue by zacekjakub** [MyEssentials/MyTown2#187] opened 2015-04-30 19:20 UTC
// Ooh. Shiny.

Time: 4/30/15 9:03 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
        at net.minecraft.entity.player.EntityPlayerMP.func_145747_a(EntityPlayerMP.java:942)
        at mytown.core.ChatUtils.sendChat(ChatUtils.java:27)
        at mytown.entities.Resident.sendMessage(Resident.java:389)
        at mytown.entities.Resident.checkLocation(Resident.java:288)
        at mytown.handlers.Ticker.checkLocationAndSendMap(Ticker.java:125)
        at mytown.handlers.Ticker.onEnterChunk(Ticker.java:115)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_127_Ticker_onEnterChunk_EnteringChunk.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:796)
        at net.minecraft.world.World.func_72866_a(World.java:2115)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
        at net.minecraft.world.World.func_72870_g(World.java:2034)
        at net.minecraft.world.World.func_72939_s(World.java:1887)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
        at net.minecraft.entity.player.EntityPlayerMP.func_145747_a(EntityPlayerMP.java:942)
        at mytown.core.ChatUtils.sendChat(ChatUtils.java:27)
        at mytown.entities.Resident.sendMessage(Resident.java:389)
        at mytown.entities.Resident.checkLocation(Resident.java:288)
        at mytown.handlers.Ticker.checkLocationAndSendMap(Ticker.java:125)
        at mytown.handlers.Ticker.onEnterChunk(Ticker.java:115)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_127_Ticker_onEnterChunk_EnteringChunk.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:796)
        at net.minecraft.world.World.func_72866_a(World.java:2115)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
        at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
        Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
        Entity ID: 4044
        Entity Name: pupy
        Entity's Exact location: -527.98, 71.00, 971.37
        Entity's Block location: World: (-528,71,971), Chunk: (at 0,4,11 in -33,60; contains blocks -528,0,960 to -513,255,975), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
        Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1887)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
        Level name: world
        All players: 4 total; [EntityPlayerMP['Jirinka'/3674, l='world', x=-563.70, y=63.00, z=963.12], EntityPlayerMP['pepino'/3916, l='world', x=-525.73, y=71.00, z=969.65], EntityPlayerMP['pupy'/4044, l='world', x=-527.98, y=71.00, z=971.37], EntityPlayerMP['net13'/9834, l='world', x=-287.69, y=63.00, z=593.74]]
        Chunk stats: ServerChunkCache: 1294 Drop: 0
        Level seed: 3553854092282337655
        Level generator: ID 02 - largeBiomes, ver 0. Features enabled: true
        Level generator options: 
        Level spawn location: World: (-38,94,679), Chunk: (at 10,5,7 in -3,42; contains blocks -48,0,672 to -33,255,687), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
        Level time: 96157622 game time, 68180755 day time
        Level dimension: 0
        Level storage version: 0x04ABD - Anvil
        Level weather: Rain time: 71798 (now: false), thunder time: 105102 (now: false)
        Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
        Minecraft Version: 1.7.10
        Operating System: Linux (amd64) version 2.6.32-042stab093.4
        Java Version: 1.8.0_31, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 679829992 bytes (648 MB) / 1553465344 bytes (1481 MB) up to 1908932608 bytes (1820 MB)
        JVM Flags: 2 total; -Xms1024M -Xmx2048M
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 103
        FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 61 mods loaded, 61 mods active
        mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        CodeChickenCore{1.0.1.8} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MobiusCore{1.2.3} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        TubesCore{${version}} [Tubes Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core] (malisiscore-1.7.10-0.10.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Trapcraft{v2.2.1a} [Trapcraft] ([1.7.10] Trapcraft - v2.3.0a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        IC2{2.2.711-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.711-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ImmibisCore{59.0.8} [Immibis Core] (immibis-core-59.0.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        AdvancedMachines{59.0.2} [Advanced Machines] (advanced-machines-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BiblioCraft{1.10.2} [BiblioCraft] (BiblioCraft[v1.10.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Core{6.4.8} [BuildCraft] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Transport{6.4.8} [BC Transport] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Silicon{6.4.8} [BC Silicon] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Builders{6.4.8} [BC Builders] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Energy{6.4.8} [BC Energy] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        BuildCraft|Factory{6.4.8} [BC Factory] (buildcraft-6.4.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        craftguide{1.6.8.1} [CraftGuide] (CraftGuide-1.6.8.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        DimensionalAnchors{59.0.2} [Dimensional Anchors] (dimensional-anchor-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        DragonsRadioMod{1.6.3} [Dragon's Radio Mod] (DragonsRadioMod-MC1.7.10-1.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MoCreatures{6.3.0} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.0(1).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ExtrabiomesXL{3.16.0} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Forestry{3.5.3.11} [Forestry for Minecraft] (forestry_1.7.10-3.5.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        IC2NuclearControl{2.1.2a} [Nuclear Control 2] (IC2NuclearControl-2.1.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        IGWMod{1.1.1-17} [In-Game wiki Mod] (IGW-Mod.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ImmibisPeripherals{59.0.2} [Immibis's Peripherals] (immibis-peripherals-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        malisisdoors{1.7.10-1.4.3} [Malisis' Doors] (malisisdoors-1.7.10-1.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MyEssentials-Core{2.0} [MyEssentials-Core] (MyEssentials-Core-1.7.10-1.6r-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MyTown2{1.7.10-0.0.2b} [MyTown 2] (MyTown2-1.7.10-0.0.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        neiintegration{1.0.3} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Railcraft{9.5.0.0} [Railcraft] (Railcraft_1.7.10-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        OCS{1.7.2} [OpenCCSensors] (openccsensors-1.7.2 .jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MrTJPCoreMod{1.0.5.11} [MrTJPCore] (MrTJPCore-1.7.10-1.0.5.11-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ProjRed|Core{4.5.15.75} [ProjectRed] (ProjectRed-1.7.10-4.5.15.75-Base.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ProjRed|Transmission{4.5.15.75} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.15.75-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        OpenComputers{1.5.6.13} [OpenComputers] (OpenComputers-MC1.7.10-1.5.6.13-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MapWriter{2.1.1} [MapWriter] (Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Opis{1.2.3} [Opis] (Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        PeripheralsPlusPlus{1.2.6} [Peripherals++] (Peripherals++-1.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        PneumaticCraft{1.6.3-65} [PneumaticCraft] (PneumaticCraft-1.7.10-1.6.3-65-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        PowerConverters{1.7.10-3.0.4.46} [Power Converters] (PowerConverters-1.7.10-3.0.4.46.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ProjRed|Transportation{4.5.15.75} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.5.15.75-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ProjRed|Compatibility{4.5.15.75} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.5.15.75-Compat.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ProjRed|Integration{4.5.15.75} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.15.75-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ProjRed|Illumination{4.5.15.75} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.15.75-Lighting.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ProjRed|Expansion{4.5.15.75} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.5.15.75-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ServerTools{1.7.10-2.2.0.79} [ServerTools] (ServerTools-CORE-1.7.10-2.2.0.79.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ServerTools-BACKUP{1.7.10-2.2.0.23} [ServerTools Backup] (ServerTools-BACKUP-1.7.10-2.2.0.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        TooMuchTime{2.4.0} [TooMuchTime] (TooMuchTime-1.7.10-2.4.0.B3-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Tubes{2.0.5} [Tubes] (Tubes-1.7.10-2.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        Tubestuff{59.0.1} [Tubestuff] (tubestuff-59.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
        MyTown|Datasource: ~~ERROR~~ NullPointerException: null
        Profiler Position: N/A (disabled)
        Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        Player Count: 4 / 60; [EntityPlayerMP['Jirinka'/3674, l='world', x=-563.70, y=63.00, z=963.12], EntityPlayerMP['pepino'/3916, l='world', x=-525.73, y=71.00, z=969.65], EntityPlayerMP['pupy'/4044, l='world', x=-527.98, y=71.00, z=971.37], EntityPlayerMP['net13'/9834, l='world', x=-287.69, y=63.00, z=593.74]]
        Is Modded: Definitely; Server brand changed to 'fml,forge'

**Comment by AfterWind** [comment] 2015-04-30 19:37
Duplicate of #186. Please refrain from posting crashes that already have been reported. We'll fix it when we can, posting it again only prevents us from fixing it faster :)

**Comment by AfterWind** [comment] 2015-06-04 16:48
Duplicate of #178. Closing.

**Closed by AfterWind** 2015-06-04 16:48 UTC
Labels: duplicate
