### ISSUE TITLE
[MyTown2-1.7.10-0.0.2b] java.lang.NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by brunyman** [MyEssentials/MyTown2#186] opened 2015-04-29 19:24 UTC
Hi, looks like i get this crash a lot, i updated my server to latest beta version about 24h ago, and i already got about 7 crashes of this type:  http://pastebin.com/8dFWdAfY
I do not know what triggers it, but i was getting this type of crash a lot on the alpha version as well. We run FTB Direwolf20 modpack for 1.7.10 on Cauldron. Thanks

**Comment by AfterWind** [comment] 2015-04-29 19:26
What version of Forge are you using?

**Comment by evernife** [comment] 2015-04-29 20:24
Same of mine :/ 
Make a refference to #178

I make an update now for the forge version 10.13.3.1395
Lets see if it persist.

**Comment by evernife** [comment] 2015-04-29 22:55
I got this with the lastest forge version.
By sigh didnt crash the server, but is flooding the console...
And seems to wasting my memory....

http://pastebin.com/pNp7mMfp

**Comment by brunyman** [comment] 2015-05-01 08:29
we use cauldron cauldron-1.7.10-1.1343.01.0 with forge MinecraftForge v10.13.2.1343

I still did not get what triggers it, looks random

**Comment by AfterWind** [comment] 2015-06-04 16:48
Duplicate of #178, closing.

**Closed by AfterWind** 2015-06-04 16:48 UTC
Labels: bug
