### ISSUE TITLE
Config Keeps resetting

### ISSUE THREAD

**Issue by groveham** [MyEssentials/MyTown2#114] opened 2015-02-23 15:32 UTC
Sorry to keep reporting all these issues, I've got the Mod on my Server and I'm running into a few issues. I've changed the following lines before, saved then uploaded to the FTP but for what ever reason, after the server restart, I check the MyTown.cfg and they have been reset back to the default. I've changed the following lines before but now they are back to defaults:

-------------------------------------------------------------
Changed this to "maxTowns=2"
residents {
    # The amount of towns a resident can be in.
    I:maxTowns=3
}

-------------------------------------------------------------
Changed this to "costAmountClaim=1"
    # The amount of the cost item you need to create a town.
    I:costAmountClaim=3
Note: the description is a little misleading. Recommend changing it to something like:
#The amount of the cost item you need to claim a block

-------------------------------------------------------------
Have changed this to "costAmountMakeTown=0"
    # The amount of the cost item you need to create a town.
    I:costAmountMakeTown=5

-------------------------------------------------------------
Using the following:
MyTown2-1.7.10-0.26a.jar
MyEssentials-Core-1.7.10-1.3-universal.jar

If you need any other information or testing please ask, happy to help.

**Comment by AfterWind** [comment] 2015-02-24 13:56
I'm still searching for the cause of this issue. If anyone finds it please tell me or make a PR it will help a lot.

**Comment by groveham** [comment] 2015-02-24 16:29
I've been looking in this, looking through the FML Log, etc. and found this:
http://pastebin.com/kNhSAz3U

I'm no expect in coding but from what I can tell the mod seems to be 'transforming' the config? I've tested without the ServerTools Mod and it seems to be keeping the values I've set in the MyTown.cfg file. Does that look like the sort of the issue or am I completely wrong?

**Comment by AfterWind** [comment] 2015-02-24 16:32
The chance it small that it has to do with other mod. Somewhere in the code, basically before the server stops or after it starts the config is regenerated. Try Closing the server, modify the configs and then start it back on.

**Comment by groveham** [comment] 2015-02-24 16:41
Yeah OK that worked. You can't edit it, shut the server down, then start it back up. That's what I was doing and it was re-creating the config and removing the changes. You have to Close the server, modify the configs and then start it back on just like you said :)

**Comment by AfterWind** [comment] 2015-02-28 19:41
Found the problem and this got fixed.

**Closed by AfterWind** 2015-02-28 19:41 UTC
Labels: bug
