### ISSUE TITLE
Town spawn command not longer works

### ISSUE THREAD

**Issue by LemADEC** [MyEssentials/MyTown2#389] opened 2015-11-09 23:05 UTC
When player tries to use /town spawn, an exception occurs in console and command won't work:
```
>op Pkr1345
[18:01:19 INFO]: CONSOLE: Opped Pkr1345
[18:01:24 INFO]: Pkr1345 issued server command: /town spawn
[18:01:24 ERROR]: Couldn't process command: 'town spawn'
java.lang.NullPointerException
>       at net.minecraft.entity.player.EntityPlayerMP.func_70634_a(EntityPlayerMP.java:1234) ~[mw.class:?]
>       at myessentials.utils.PlayerUtils.teleport(PlayerUtils.java:223) ~[PlayerUtils.class:?]
>       at mytown.entities.Town.sendToSpawn(Town.java:166) ~[Town.class:?]
>       at mytown.commands.CommandsEveryone.spawnCommand(CommandsEveryone.java:92) ~[CommandsEveryone.class:?]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_85]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_85]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_85]
>       at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_85]
>       at mypermissions.command.CommandTreeNode.commandCall(CommandTreeNode.java:72) ~[CommandTreeNode.class:?]
>       at mypermissions.command.CommandTree.commandCall(CommandTree.java:40) ~[CommandTree.class:?]
>       at mypermissions.command.CommandModel.func_71515_b(CommandModel.java:46) ~[CommandModel.class:?]
>       at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:99) [z.class:?]
>       at org.bukkit.craftbukkit.v1_7_R4.command.CraftSimpleCommandMap.dispatch(CraftSimpleCommandMap.java:53) [CraftSimpleCommandMap.class:1.7.10-1492.152]
>       at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchVanillaCommand(CraftServer.java:733) [CraftServer.class:1.7.10-1492.152]
>       at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1324) [nh.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
>       at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
>       at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
>deop Pkr1345
[18:01:28 INFO]: CONSOLE: De-opped Pkr1345
```

Config is set to B:fullAccessForOPS=true

Issue wasn't present with:
MyEssentials-Core-1.7.10-95-dev.jar
MyPermissions-1.7.10-43-dev.jar
MyTown2-1.7.10-291-dev.jar

Issue is reproduced with:
MyEssentials-Core-1.7.10-95-dev.jar
MyPermissions-1.7.10-46-dev.jar
MyTown2-1.7.10-296-dev.jar

Player isn't the Mayor.

**Comment by krwminer** [comment] 2015-11-10 00:38
So with the exact same world/everything if you switch back to the old rev of MyTown2 and MyPermissions you do not have any errors?

Where is the town spawn set too?
Does the player have to be OP for this to happen?

Looks like a kcauldron server, please give details.

I will try and re-create on my test kcauldron server, but more details will be helpful.

**Comment by LemADEC** [comment] 2015-11-10 01:05
That player was using /town spawn routinely, without being OP
I've updated the server with latest version
That player started to have issue, I was seeing those exception on console, he was still not being OP
I've tried myself, being OP and mayor of my town, I had no issue
I've OP him to try if it's a perm issue, issue was still there
I've another player OP, resident in my town, she had no issue

I guess there's something off in that guy town, maybe?

I didn't try to rollback the world or mods version

**Comment by LemADEC** [comment] 2015-11-10 01:15
Here's a quick dump of the database for this player and his town, nothing special from I can see:
![image](https://cloud.githubusercontent.com/assets/4776032/11051519/41f6e1fe-8750-11e5-9a78-34c2109d95b9.png)

![image](https://cloud.githubusercontent.com/assets/4776032/11051541/732321de-8750-11e5-8663-2c3a2f7fb40b.png)

![image](https://cloud.githubusercontent.com/assets/4776032/11051551/898bf8ce-8750-11e5-98a0-ad4fcc4f39bf.png)

![image](https://cloud.githubusercontent.com/assets/4776032/11051571/9f235e66-8750-11e5-8e7e-fefaacff7172.png)

![image](https://cloud.githubusercontent.com/assets/4776032/11051583/acad9042-8750-11e5-9203-cae48c829504.png)

![image](https://cloud.githubusercontent.com/assets/4776032/11051594/c2d39bb4-8750-11e5-9480-84f818fa58a7.png)

**Comment by krwminer** [comment] 2015-11-10 03:10
If you teleport to his town spawn with a /ta command does it crash?

**Comment by LemADEC** [comment] 2015-11-10 09:41
Not sure about using /ta since it started to work again.
It might have been fixed when his mayor connected on the server. They both said that spawn location was not changed.

**Comment by krwminer** [comment] 2015-11-10 21:22
Hmm. So is it working only when the mayor of the town is connected or all the time now that the mayor has connected again?

**Comment by krwminer** [comment] 2015-11-12 22:18
Can you reproduce this anymore?

**Comment by LemADEC** [comment] 2015-11-12 23:32
That player didn't reconnect yet, should be good this week end.

**Comment by LemADEC** [comment] 2015-11-16 22:18
That player tried again and it didn't reproduce the issue while mayor was already online.
We've rebooted and he connected, tried to /town spawn and it works (mayor only connected later on).
We've tested with a few other players to no avail.

The only thing that changed is the spawn location for that town, a chest was at the spot or just next to it.

**Comment by krwminer** [comment] 2015-11-17 00:00
I think I will close this. Please reopen if it occurs again. You should not have spawn right next to things in general.

**Closed by krwminer** 2015-11-17 00:00 UTC
