### ISSUE TITLE
crops

### ISSUE THREAD

**Issue by dezil** [MyEssentials/MyTown2#370] opened 2015-10-25 23:04 UTC
vanilla crops and crops from other mods (only agri craft tested) can be broken by outsiders by them jumping on the crops

**Comment by AfterWind** [comment] 2015-10-26 13:41
Duplicate of #139. It is fairly difficult so it's of smaller priority right now. :/

**Closed by AfterWind** 2015-10-26 13:41 UTC

**Comment by Callum-MM** [comment] 2015-10-28 23:16
A temporary fix could be to make a plot where the farm is and set the entry flag to false. If you want to give people access then add them to the plot. It doesn't stop trampling, but it stops random people trampling them.
