### ISSUE TITLE
Return of the SERVER_ADMINS

### ISSUE THREAD

**Issue by Flenix** [MyEssentials/MyTown2#376] opened 2015-10-29 17:16 UTC
An old issue I had (https://github.com/MyEssentials/MyTown2/issues/289) seems to have returned. When a player makes a town, it's claiming the town as SERVER_ADMINS and telling him the land is already claimed. The town has zero claims, but the name is then used. The player can try making as many towns as they want, and it does this every time.
It seems to be player specific, as only happens to certain players (Or it did last time - I've not been able to test enough this time around)

The latest instance was happening with a new player called PHAT_Boy, trying to make a town called Col. There's a total of 40 towns on the server, 38 player owned, one actually owned by SERVER_ADMINS and then his town, which is also claimed as SERVER_ADMINS.
In case it's UUID-related, here's a sample of UUIDs from my server. PHAT_Boy is the problem player, while the others listed are all long term players who have the largest towns. 
http://pastebin.com/cGDLKv3R

We tested town creation with only that one player online, where the TPS was a solid 20, however when he initially joined the server there was 5 players online and the TPS was roughly 17.5 (due to a player flying a plane and loading chunks quickly)

Here's some configs:
DefaultFlags.json: http://pastebin.com/YS5STzsZ
DefaultTownRanks.json: http://pastebin.com/ZvQKW0uE
MyTown.cfg*: http://pastebin.com/WTaZp2A6
WildPerms: http://pastebin.com/1yJLPLEG
*Obviously DB info is removed.

We're using a MySQL database located on the same server.
Full mod list: http://ctrlv.in/660031

And finally, the server itself: https://www.hetzner.de/gb/hosting/produkte_rootserver/ex40 - 16GB of RAM is dedicated to the Minecraft instance. Only other things running on the server are a Jenkins installation (which hasn't been used for over a week), a TeamSpeak server and an IRC bot.

Let me know if you need anything else.

**Comment by krwminer** [comment] 2015-11-07 19:35
I am going to close this down. Please re-open it if you ever get this error again. I will leave the debug in so we can narrow down the cause.

**Closed by krwminer** 2015-11-07 19:35 UTC
