### ISSUE TITLE
WORLD PROTECTION

### ISSUE THREAD

**Issue by LargePrime** [MyEssentials/MyTown2#23] opened 2014-07-05 19:41 UTC
I was asking in IRC so i thought to report it here.  Please mark as feature request.

I am requesting a feature to have mytown protect the whole world, and you have to claim any place to mine or harvest any item.  Additionally if the claim is removed the area of the claim is slowly restored back to a virgin state.

This reduces the server map from looking bad in a short time as people come on then leave and there are partial houses and mines all over the map.

I believe Grief prevention has this feature.

there are potential abuses in that some really rare items may be able to constantly be reharvested by claiming and removing the claim until it is restored.  It seems one may have a list of items that are not regenerated or other simple fixes.  see griefprotection

Thanks for your work on mytown.

**Comment by AfterWind** [comment] 2015-03-16 18:40
Wild protection already implemented. Rest is duplicate of #8

**Closed by AfterWind** 2015-03-16 18:40 UTC
Labels: enhancement
