### ISSUE TITLE
Null Pointer Exception [0.2.0b]

### ISSUE THREAD

**Issue by stevestech** [MyEssentials/MyTown2#349] opened 2015-10-16 00:07 UTC
After starting a FTB Banished 1.3.0 server with stock Forge 10.13.4.1448, I've seen the following NPE pop up a couple of times with MyTown2 0.2.0b. I reset the database, but saw it come back again. The NPE occurs every time a certain chunk is loaded with MyTown enabled.

I also tried with MyTown2 0.1.1b and got the same NPE after a while, interestingly. (I deleted the database when switching versions).

```
java.lang.NullPointerException: Exception in server tick loop
	at mytown.protection.segment.getter.Getters.getValue(Getters.java:184)
	at mytown.protection.segment.SegmentEntity.getOwner(SegmentEntity.java:37)
	at mytown.protection.Protection.checkEntity(Protection.java:114)
	at mytown.protection.Protections.worldTick(Protections.java:128)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_205_Protections_worldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:620)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

```
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448
	UCHIJAAAA	MyEssentials-Core{1.7.10-1.13r} [MyEssentials-Core] (MyEssentials-Core-1.7.10-1.13r-universal.jar) 
	UCHIJAAAA	MyPermissions{1.7.10-0000r} [MyPermissions] (MyPermissions-1.7.10-31-dev.jar) 
	UCHIJAAAA	MyTown2{1.7.10-0.2.0b} [MyTown 2] (MyTown2-1.7.10-0.2.0b.jar) 
```
http://paste.ubuntu.com/12794776/

```
	UCHIJAAAA	MyEssentials-Core{1.7.10-1.10r} [MyEssentials-Core] (MyEssentials-Core-1.7.10-1.10r-universal.jar) 
	UCHIJAAAA	MyTown2{1.7.10-0.1.1b} [MyTown 2] (MyTown2-1.7.10-0.1.1b.jar)
```
http://paste.ubuntu.com/12794774/

**Comment by AfterWind** [comment] 2015-10-16 12:33
This has to do with protections, so deleting the database won't do anything.
This is a duplicate of:
https://github.com/MyEssentials/MyTown2/issues/341
Look in there for the fix.

**Closed by AfterWind** 2015-10-16 12:33 UTC

**Comment by stevestech** [comment] 2015-10-17 05:54
Thank you
