### ISSUE TITLE
/t spawn from the end causes black screen

### ISSUE THREAD

**Issue by oryfoxer7410** [MyEssentials/MyTown2#198] opened 2015-05-14 19:40 UTC
If you do /t spawn from the end, it will black out your screen. Once you log off and and back, you will be at your town spawn.

I have not tested this with other dimensions, but I know for sure the end does this. Seen multiple times for multiple users, pretty consistent.

**Comment by evernife** [comment] 2015-05-14 19:45
Yes, already reported. Problens with "/t spawn" (teleportation)

It is related with #189

**Comment by AfterWind** [comment] 2015-06-05 15:30
Duplicate of #189. Closing.

**Closed by AfterWind** 2015-06-05 15:30 UTC
Labels: duplicate
