### ISSUE TITLE
[0.1.2b] java.lang.NoClassDefFoundError: mypermissions/api/IPermissionManager

### ISSUE THREAD

**Issue by brunyman** [MyEssentials/MyTown2#273] opened 2015-08-06 06:53 UTC
Crash: http://pastebin.com/FVFfVhh3

Server crashes on startup. Modpack FTB Direwolf v1.6.1
KCauldron-1.7.10-1492.150

**Comment by AfterWind** [comment] 2015-08-06 15:29
You need MyPermissions. But as the project is not yet approved on CurseForge you need to wait for us to be able to release it. Sorry about that.

**Comment by brunyman** [comment] 2015-08-07 05:43
ok :P, good to know that it will get on CurseForge :P, are there any permission nodes changed from version 0.1.1b ?

**Comment by gatekeeper258** [comment] 2015-08-07 15:43
I'm having the same issue. I have mc1.7.10, forge 1448, but I am using ForgeEssentials for perms which is compatable. I have both the myTown2 and myessentials installed as required.

...
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 8/7/15 11:38 AM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mypermissions/api/IPermissionManager
        at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
        at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: mypermissions/api/IPermissionManager
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
...

**Comment by AfterWind** [comment] 2015-08-07 19:10
MyPermissions is more of a bridge between our mods and FE/Bukkit permissions system, this is why it's a direct dependency of MyTown2. If the project doesn't get approved anytime soon (which it should) we will provide our own links very soon.

**Comment by gatekeeper258** [comment] 2015-08-08 03:31
ah, my bad, I wasnt even aware of MyPermissions. I thought FE(Forge Essentials) was an all in one ala perms/vault from back in the bukkit days brought to forge. So up till now mytown2 isnt forge ready until myPerms is released?

**Comment by AfterWind** [comment] 2015-08-10 02:10
Fixed in 0.1.3b

**Closed by AfterWind** 2015-08-10 02:10 UTC
