### ISSUE TITLE
Server Crash when Ars Magica Projectile Enters Void

### ISSUE THREAD

**Issue by 0zlw** [MyEssentials/MyTown2#373] opened 2015-10-28 11:13 UTC
Two identical crashes occurred related to MyTown, ~~in which a player has reported that they had lava entering the void within their town borders both times~~. The modpack is Banished.

See update below: Caused by projectile firing into the void inside a town

http://pastebin.com/NVSwt0Tg
http://pastebin.com/eL7YD3SE

**Comment by AfterWind** [comment] 2015-10-28 12:06
Lava can't enter in the void. It's impossible. The crash was caused by something else.
From the crash report I can tell it was an entity (maybe in the void) causing this, but I am not sure.
Did he do anything else other than letting lava go in the void?

**Comment by 0zlw** [comment] 2015-10-28 12:07
Yeah obviously the lava didn't enter the void, but that is what the player is telling me reproduces it.

**Comment by 0zlw** [comment] 2015-10-28 12:27
User has caused 2 more of these crashes. He reports that it occurs both when lava drops, and when too many entities fall into the nether.

**Comment by 0zlw** [comment] 2015-10-28 12:47
Okay after watching the user reproduce the crash I believe it's to do with the entities that the ars magica dig projectile spell throws out. The MyTown error occurs when these projectiles directly hit the void, so yeah... the lava and the entities is just a byproduct.

**Comment by krwminer** [comment] 2015-10-28 14:07
Fixed in MT2 dev build 277.

**Closed by krwminer** 2015-10-28 14:07 UTC
Labels: bug
