### ISSUE TITLE
Breeding inside town claims

### ISSUE THREAD

**Issue by LemADEC** [MyEssentials/MyTown2#386] opened 2015-11-05 23:19 UTC
We've been unable to breed animals in claimed land (XP drops but baby doesn't appear to player, console remains silent).
The same works just fine in the wilderness.

This is with
MyTown2-1.7.10-291-dev.jar
MyPermissions-1.7.10-43-dev.jar
MyEssentials-Core-1.7.10-95-dev.jar
using $MyPermission permission system.

I've tried changing a few perms in the town but it didn't help.

Is there any specifics I'm missing?

**Comment by krwminer** [comment] 2015-11-06 01:44
I tried this with same version of everything you have listed above, (except MyPermissions were 45), and I did not see a problem. I do not see how the minor difference in MyPermissions would make any difference.

If you do not have permissions to right-click the animals with food, then it should give you a protection error, (although you might still see hearts from the animals). But you should not get XP in that case.

If the entities flags is set to false then the parent animals should vanish.

Any other details you can provide might be helpful for me to reproduce it.

**Comment by LemADEC** [comment] 2015-11-06 08:51
Here are the perms currently applied in the town:
![image](https://cloud.githubusercontent.com/assets/4776032/10992917/0bcd641e-846b-11e5-90ce-587fc27d9c00.png)

It's happening with the FTB Infinity pack running on KCauldron-1.7.10-1492.152-server.
There's no plot in the town.
We've tried with cows and pigs, same behavior.

**Comment by krwminer** [comment] 2015-11-06 14:12
Are you a resident to the town or an outsider?

**Comment by LemADEC** [comment] 2015-11-06 22:30
I'm Mayor of the town and she was Resident. Both of us gave same result.

**Comment by krwminer** [comment] 2015-11-06 22:36
Hmm. The only other thing I can think to have you try is to set mobs to true and try it again in that town.

I will also try and get my kcauldron test setup to match the versions you mentioned.

**Comment by krwminer** [comment] 2015-11-06 22:43
Also what exact version for FTB Infinity are you running? I see several out there.

**Comment by LemADEC** [comment] 2015-11-07 01:03
I'm using FTB Infinity 2.0.2.
I've tried setting mobs to true (seeing zombies spawning in town) and issue is still present.

**Comment by LemADEC** [comment] 2015-11-07 01:03
I did install all the protection patches available, so it might be one of them interfering?

**Comment by krwminer** [comment] 2015-11-07 01:57
It could be. I am really not sure how MT2 could be doing it. I will try and set it up, just in case it is something I missed.

**Comment by krwminer** [comment] 2015-11-07 03:28
OK. Tried it out and it worked. The only difference in our setups are I used Kcauldron 1448, since Forge 1448 is what is suggested for the server. I also used all the latest MT2/MEC/MyPermissions. Lastly I did not install any protection plugins or such.

At this point I think I will close the issue. You can open it back up again if you really feel it is something in MT2.

**Closed by krwminer** 2015-11-07 03:28 UTC

**Comment by LemADEC** [comment] 2015-11-07 11:38
Thanks for your help.
Issue has been fixed. It wasn't related to Forge version, Cauldron version, nor protection plugin, nor MT2.
